# Your Website Title
title: Jeferson Januario

# Your Website URL
url: 'http://jjanuario.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Jeferson Januario
tagline: Machine Learning, IoT, Computer Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Smart Automation, IoT, Computer Engineering
description_tiny: 'Home: Brasil | Studied: Computer Enginner IBTA | Work: <a href="https://asterixsolucoes.com.br">Asterix Soluções<a/>'
email: jeferson.januario@gmail.com
website: jjanuario.github.io # do not add http://
linkedin: jeferson-januario-9547b04a
github: jjanuario
twitter: '@jefersonjanuari'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
